/**
 * Action types for loading
 */

export default {
  LOGIN_LOADING: 'LOGIN_LOADING',
  LOGIN_LOADED: 'LOGIN_LOADED',
  CONTACTS_LOADING: 'CONTACTS_LOADING',
  CONTACTS_LOADED: 'CONTACTS_LOADED',
};
