export default {
  REQUEST_CONTACTS: 'REQUEST_CONTACTS',
  LOGOUT: 'LOGOUT',
  UPDATE_LOGIN: 'UPDATE_LOGIN',
  UPDATE_LOGIN_LOCAL: 'UPDATE_LOGIN_LOCAL',
  REQUEST_LOGIN: 'REQUEST_LOGIN',
  UPDATE_CONTACTS: 'UPDATE_CONTACTS',
  STORE_WALLET: 'STORE_WALLET',
};
